workflow edit

diff --git a/.github/workflows/django_ci.yml b/.github/workflows/django_ci.yml
--- a/.github/workflows/django_ci.yml
+++ b/.github/workflows/django_ci.yml
@@ -17,24 +17,33 @@ jobs:
           - 6379:6379
 
     steps:
-    - uses: actions/checkout@v2
+    - name: Checkout code
+      uses: actions/checkout@v2
+
     - name: Set up Python 3.8
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
+
     - name: Install dependencies
       run: |
         pip install --upgrade pip
         pip install -r requirements.txt
+
     - name: Run tests
       run: |
         python manage.py test
+
   deploy:
     runs-on: ubuntu-latest
     needs: build
     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
     steps:
-    - uses: actions/checkout@v2
+    - name: Checkout code
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0  # Ensures all history is fetched
+
     - name: Deploy to VPS
       uses: appleboy/ssh-action@master
       with:
@@ -42,6 +51,7 @@ jobs:
         username: ${{ secrets.VPS_USERNAME }}
         password: ${{ secrets.VPS_PASSWORD }}
         script: |
+          set -e  # Exit immediately if a command exits with a non-zero status
           cd /var/www/directory_listing
           git stash 
           git pull origin main 
